import type { ReadingText } from './reading-library';
// Original decodable miniatures. Early poems are explicitly labelled rhythm exercises.
export const topicTexts: ReadingText[] = [
  {
    id: 'topic-call-mum',
    kind: 'sentences',
    title: 'Мама! Ау!',
    lines: ['Мама! Ау!'],
    question: 'Кого зовут?',
    options: ['Мама', 'Ау'],
    answer: 'Мама',
    hint: 'Послушай вопрос и перечитай строку.',
  },
  {
    id: 'topic-mum-call',
    kind: 'sentences',
    title: 'Ау, мама!',
    lines: ['Ау, мама!'],
    question: 'Как зовут маму?',
    options: ['Ау', 'Му'],
    answer: 'Ау',
    hint: 'Послушай вопрос и перечитай строку.',
  },
  {
    id: 'topic-mum-home',
    kind: 'sentences',
    title: 'Мама дома.',
    lines: ['Мама дома.'],
    question: 'Кто дома?',
    options: ['Мама', 'Папа'],
    answer: 'Мама',
    hint: 'Послушай вопрос и перечитай строку.',
  },
  {
    id: 'topic-fly',
    kind: 'sentences',
    title: 'Муха! Ах!',
    lines: ['Муха! Ах!'],
    question: 'Кого увидели?',
    options: ['Муха', 'Мама'],
    answer: 'Муха',
    hint: 'Послушай вопрос и перечитай строку.',
  },
  {
    id: 'topic-ear',
    kind: 'sentences',
    title: 'У мамы ухо.',
    lines: ['У мамы ухо.'],
    question: 'Что у мамы?',
    options: ['Ухо', 'Нос'],
    answer: 'Ухо',
    hint: 'Послушай вопрос и перечитай строку.',
  },
  {
    id: 'topic-catfish',
    kind: 'sentences',
    title: 'У сома усы.',
    lines: ['У сома усы.'],
    question: 'Что у сома?',
    options: ['Усы', 'Ухо'],
    answer: 'Усы',
    hint: 'Послушай вопрос и перечитай строку.',
  },
  {
    id: 'topic-wasp',
    kind: 'sentences',
    title: 'Оса у мха.',
    lines: ['Оса у мха.'],
    question: 'Кто у мха?',
    options: ['Оса', 'Сом'],
    answer: 'Оса',
    hint: 'Послушай вопрос и перечитай строку.',
  },
  {
    id: 'topic-pine',
    kind: 'sentences',
    title: 'У сосны мох.',
    lines: ['У сосны мох.'],
    question: 'Что у сосны?',
    options: ['Мох', 'Оса'],
    answer: 'Мох',
    hint: 'Послушай вопрос и перечитай строку.',
  },
  {
    id: 'topic-moon',
    kind: 'sentences',
    title: 'Луна мала.',
    lines: ['Луна мала.'],
    question: 'Что мало?',
    options: ['Луна', 'Сом'],
    answer: 'Луна',
    hint: 'Послушай вопрос и перечитай строку.',
  },
  {
    id: 'topic-elephant',
    kind: 'sentences',
    title: 'Слон у сосны.',
    lines: ['Слон у сосны.'],
    question: 'Кто у сосны?',
    options: ['Слон', 'Оса'],
    answer: 'Слон',
    hint: 'Послушай вопрос и перечитай строку.',
  },
  {
    id: 'topic-mum-frame',
    kind: 'sentences',
    title: 'Мама мыла раму.',
    lines: ['Мама мыла раму.'],
    question: 'Что мыла мама?',
    options: ['Раму', 'Луну'],
    answer: 'Раму',
    hint: 'Послушай вопрос и перечитай строку.',
  },
  {
    id: 'topic-dew',
    kind: 'sentences',
    title: 'У сосны роса.',
    lines: ['У сосны роса.'],
    question: 'Что у сосны?',
    options: ['Роса', 'Сыр'],
    answer: 'Роса',
    hint: 'Послушай вопрос и перечитай строку.',
  },
  {
    id: 'topic-poppy',
    kind: 'sentences',
    title: 'У мамы мак.',
    lines: ['У мамы мак.'],
    question: 'Что у мамы?',
    options: ['Мак', 'Сыр'],
    answer: 'Мак',
    hint: 'Послушай вопрос и перечитай строку.',
  },
  {
    id: 'topic-onion',
    kind: 'sentences',
    title: 'Лук у окна.',
    lines: ['Лук у окна.'],
    question: 'Что у окна?',
    options: ['Лук', 'Мак'],
    answer: 'Лук',
    hint: 'Послушай вопрос и перечитай строку.',
  },
  {
    id: 'topic-cat',
    kind: 'sentences',
    title: 'Кот у окна.',
    lines: ['Кот у окна.'],
    question: 'Кто у окна?',
    options: ['Кот', 'Сом'],
    answer: 'Кот',
    hint: 'Послушай вопрос и перечитай строку.',
  },
  {
    id: 'topic-cake',
    kind: 'sentences',
    title: 'У мамы торт.',
    lines: ['У мамы торт.'],
    question: 'Что у мамы?',
    options: ['Торт', 'Кот'],
    answer: 'Торт',
    hint: 'Послушай вопрос и перечитай строку.',
  },
  {
    id: 'topic-fox',
    kind: 'sentences',
    title: 'Лиса у сосны.',
    lines: ['Лиса у сосны.'],
    question: 'Кто у сосны?',
    options: ['Лиса', 'Кит'],
    answer: 'Лиса',
    hint: 'Послушай вопрос и перечитай строку.',
  },
  {
    id: 'topic-sled',
    kind: 'sentences',
    title: 'У Иры сани.',
    lines: ['У Иры сани.'],
    question: 'Что у Иры?',
    options: ['Сани', 'Нитки'],
    answer: 'Сани',
    hint: 'Послушай вопрос и перечитай строку.',
  },
  {
    id: 'topic-dad',
    kind: 'sentences',
    title: 'Папа пилит.',
    lines: ['Папа пилит.'],
    question: 'Кто пилит?',
    options: ['Папа', 'Мама'],
    answer: 'Папа',
    hint: 'Послушай вопрос и перечитай строку.',
  },
  {
    id: 'topic-cat-sleep',
    kind: 'sentences',
    title: 'Кот спит.',
    lines: ['Кот спит.'],
    question: 'Что делает кот?',
    options: ['Спит', 'Пилит'],
    answer: 'Спит',
    hint: 'Послушай вопрос и перечитай строку.',
  },
  {
    id: 'topic-story-call',
    kind: 'stories',
    title: 'Мама! Ау!',
    lines: ['— Мама! Ау!', '— Ау!'],
    question: 'Как перекликаются?',
    options: ['Ау', 'Му'],
    answer: 'Ау',
    hint: 'Найди ответ в этих строках.',
  },
  {
    id: 'topic-story-echo',
    kind: 'stories',
    title: 'Ау, мама!',
    lines: ['— Ау, мама!', '— Ау, ау!'],
    question: 'Кого зовут?',
    options: ['Мама', 'Ау'],
    answer: 'Мама',
    hint: 'Найди ответ в этих строках.',
  },
  {
    id: 'topic-story-fly',
    kind: 'stories',
    title: 'Муха у мха.',
    lines: ['Муха у мха.', 'Мама: «Ах, муха!»'],
    question: 'Кто у мха?',
    options: ['Муха', 'Мама'],
    answer: 'Муха',
    hint: 'Найди ответ в этих строках.',
  },
  {
    id: 'topic-story-pine',
    kind: 'stories',
    title: 'У сосны мох.',
    lines: ['У сосны мох.', 'У мха оса.'],
    question: 'Кто у мха?',
    options: ['Оса', 'Сосна'],
    answer: 'Оса',
    hint: 'Найди ответ в этих строках.',
  },
  {
    id: 'topic-story-frame',
    kind: 'stories',
    title: 'Мама мыла раму.',
    lines: ['Мама мыла раму.', 'Мама мыла, мыла.'],
    question: 'Что мыла мама?',
    options: ['Раму', 'Сыр'],
    answer: 'Раму',
    hint: 'Найди ответ в этих строках.',
  },
  {
    id: 'topic-story-poppy',
    kind: 'stories',
    title: 'У мамы мак.',
    lines: ['У мамы мак.', 'Мак у окна.'],
    question: 'Что у окна?',
    options: ['Мак', 'Лук'],
    answer: 'Мак',
    hint: 'Найди ответ в этих строках.',
  },
  {
    id: 'topic-story-cat',
    kind: 'stories',
    title: 'Кот у окна.',
    lines: ['Кот у окна.', 'У кота усы.'],
    question: 'Что у кота?',
    options: ['Усы', 'Торт'],
    answer: 'Усы',
    hint: 'Найди ответ в этих строках.',
  },
  {
    id: 'topic-story-fox',
    kind: 'stories',
    title: 'Лиса у сосны.',
    lines: ['Лиса у сосны.', 'У сосны сани.'],
    question: 'Что у сосны?',
    options: ['Сани', 'Нитки'],
    answer: 'Сани',
    hint: 'Найди ответ в этих строках.',
  },
  {
    id: 'topic-story-dad',
    kind: 'stories',
    title: 'Папа пилит.',
    lines: ['Папа пилит.', 'Кот спит у окна.'],
    question: 'Кто спит?',
    options: ['Кот', 'Папа'],
    answer: 'Кот',
    hint: 'Найди ответ в этих строках.',
  },
  {
    id: 'topic-rhythm-call',
    kind: 'poems',
    title: 'Ритмическая разминка: Ау, ау!',
    lines: ['Ау, ау!', 'Мама, ау!'],
    question: 'Кого зовут?',
    options: ['Мама', 'Ау'],
    answer: 'Мама',
    hint: 'Это короткая ритмическая разминка. Перечитай строки.',
  },
  {
    id: 'topic-rhythm-call-two',
    kind: 'poems',
    title: 'Ритмическая разминка: Мама! Мама!',
    lines: ['Мама! Мама!', 'Ау! Ау!'],
    question: 'Как зовут?',
    options: ['Ау', 'Му'],
    answer: 'Ау',
    hint: 'Это короткая ритмическая разминка. Перечитай строки.',
  },
  {
    id: 'topic-rhythm-wasp',
    kind: 'poems',
    title: 'Ритмическая разминка: Оса, оса!',
    lines: ['Оса, оса!', 'У сома усы.'],
    question: 'У кого усы?',
    options: ['У сома', 'У осы'],
    answer: 'У сома',
    hint: 'Это короткая ритмическая разминка. Перечитай строки.',
  },
];
