/** Focused integration regressions for the three reported onboarding-0.7.2 defects. */
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {fileURLToPath} from 'node:url';
import * as E from './source/engine.mjs';
import * as R from './source/route.mjs';
import {exampleCorrectResponse} from './source/grading.mjs';
import * as P from './entry_planner.mjs';
const root=fileURLToPath(new URL('.',import.meta.url));
const pkg=JSON.parse(fs.readFileSync(root+'source/curriculum.json'));
const r=JSON.parse(fs.readFileSync(root+'entry_registry.json'));
const A={companionAvailable:true,instructionsReadable:true,canUseButtons:true};
const KOT='task.da596b8cb7c9';
function fresh(id='regression') {return E.beginVisit(E.createProfile(id),'r-visit-1',{budget:30});}
function practiceWithHelp(args={level:2},id=KOT){let p=R.launchFree(fresh(),pkg,id,{instanceId:'helped'});p=E.requestHelp(p,pkg,args);return E.recordAttempt(p,pkg,{instanceId:'helped',response:exampleCorrectResponse(pkg.items[id])});}
function entrySkill(p,skill){return E.confirmEntrySkill(p,pkg,skill,{verifier:'companion',reason:'synthetic regression fixture, not learner data'});}
function dueReview(){
 let p=E.createProfile('retention');p.knownLetters=Object.keys(pkg.letterSupport).map(x=>x.slice('letter.'.length));p.availableCapabilities=Object.keys(pkg.capabilitySupports);p=E.switchProgram(p,P.P1,pkg);
 const n=pkg.nodes['p1.A01'];
 for(let i=0;i<2;i++){
  p=E.beginVisit(p,'learn-'+i,{budget:30});const id=n.checkIds[i];
  p=E.presentTask(p,pkg,{instanceId:'check-'+i,itemId:id,nodeId:n.id,context:'route',phase:'independent',mode:'read'});
  p=E.recordAttempt(p,pkg,{instanceId:'check-'+i,response:exampleCorrectResponse(pkg.items[id])});
  if(i===1){p=E.presentTask(p,pkg,{instanceId:'application',itemId:n.applicationId,nodeId:n.id,context:'route',phase:'application',mode:'read'});p=E.recordAttempt(p,pkg,{instanceId:'application',response:exampleCorrectResponse(pkg.items[n.applicationId])});p=E.updateNodeEvidence(p,pkg,n.id);}
  p=E.endVisit(p);
 }
 assert.equal(p.skillBasis['blend.cv'].status,'pending_retention');
 while(p.completedVisits.length<4){p=E.beginVisit(p,'interval-'+p.completedVisits.length,{budget:30});p=E.endVisit(p);}
 return E.beginVisit(p,'retention-visit',{budget:30});
}
function expectUnknown(fn){assert.throws(fn,e=>e instanceof P.EntryDataError&&e.code==='UNKNOWN_ENTRY_GROUP');}
export function registerHotfixTests(test){
 test('H01 visual scaffold is logged immediately as a prompt for canonical KOT',()=>{let p=R.launchFree(fresh(),pkg,KOT,{instanceId:'visual'});p=E.requestHelp(p,pkg,{level:2});assert(p.exposures.events.some(e=>e.visitId===p.currentVisit.id&&e.promptedTexts.includes('КОТ')));assert(E.wasTargetPromptedThisVisit(p,'кот'));assert.equal(p.activeInstance.readingTargetAudioPlayed,false);});
 test('H02 completed visually assisted practice is rejected by selectProbe in same visit',()=>{const p=practiceWithHelp();const out=P.selectProbe(r,p,'CVC');assert.notEqual(out.itemId,KOT);assert(out.rejections.some(x=>x.itemId===KOT&&x.reason==='prompted_this_visit'));assert.equal(out.text,'РАК');});
 test('H03 audio and disclosed answers retain same-visit prompt protection',()=>{for(const args of [{level:0,targetAudio:true},{level:0,revealAnswer:true}]){const out=P.selectProbe(r,practiceWithHelp(args),'CVC');assert.notEqual(out.itemId,KOT);assert.equal(out.rejections[0].reason,'prompted_this_visit');}});
 test('H04 target pointers at help level one also exclude same-visit retesting',()=>{assert.notEqual(P.selectProbe(r,practiceWithHelp({level:1}),'CVC').itemId,KOT);});
 test('H05 zero target help does not falsely exclude familiar KOT',()=>{const p=practiceWithHelp({level:0});assert(!E.wasTargetPromptedThisVisit(p,'КОТ'));assert.equal(P.selectProbe(r,p,'CVC').itemId,KOT);});
 test('H06 legacy completed helpLevel=2 survives absent promptedTexts history',()=>{const p=practiceWithHelp();for(const e of p.exposures.events)e.promptedTexts=[];assert(E.wasTargetPromptedThisVisit(p,'КОТ'));assert.notEqual(P.selectProbe(r,p,'CVC').itemId,KOT);});
 test('H07 legacy active helped instance is protected before completion',()=>{let p=R.launchFree(fresh(),pkg,KOT,{instanceId:'active-help'});p=E.requestHelp(p,pkg,{level:2});for(const e of p.exposures.events)e.promptedTexts=[];assert(E.wasTargetPromptedThisVisit(p,'КОТ'));assert.notEqual(P.selectProbe(r,p,'CVC').itemId,KOT);});
 test('H08 serialization does not lose prompt history or the legacy fallback',()=>{let p=practiceWithHelp();p=JSON.parse(JSON.stringify(p));assert(E.wasTargetPromptedThisVisit(p,'КОТ'));for(const e of p.exposures.events)e.promptedTexts=[];p=JSON.parse(JSON.stringify(p));assert.notEqual(P.selectProbe(r,p,'CVC').itemId,KOT);});
 test('H09 familiar target is available on a new visit without resetting history',()=>{let p=practiceWithHelp();p=E.beginVisit(E.endVisit(p),'r-visit-2',{budget:30});assert(!E.wasTargetPromptedThisVisit(p,'КОТ'));assert.equal(P.selectProbe(r,p,'CVC').itemId,KOT);assert(p.exposures.words.includes('КОТ'));assert.equal(p.attempts[0].helpLevel,2);});
 test('H10 a new visit does not make a formerly seen NEWCV2 word unseen again',()=>{const id=r.groups.NEWCV2.orderedItemIds[0];let p=practiceWithHelp({level:2},id);p=E.beginVisit(E.endVisit(p),'r-visit-2',{budget:30});const out=P.selectProbe(r,p,'NEWCV2');assert.notEqual(out.itemId,id);assert(out.rejections.some(x=>x.itemId===id&&x.reason==='target_already_seen'));});
 test('H11 help through another taskId still blocks the same canonical KOT',()=>{const other=Object.values(pkg.items).find(i=>i.id!==KOT&&i.learnerText==='КОТ'&&i.kind==='read');assert(other);const p=practiceWithHelp({level:2},other.id);assert.notEqual(P.selectProbe(r,p,'CVC').itemId,KOT);});
 test('H12 forced launch cannot override promptFreeAtPresentation with optimistic metadata',()=>{let p=practiceWithHelp();p=R.launchFree(p,pkg,KOT,{instanceId:'forced'});assert.equal(p.activeInstance.promptFreeAtPresentation,false);p=E.recordAttempt(p,pkg,{instanceId:'forced',response:exampleCorrectResponse(pkg.items[KOT])});const observation=P.evaluateAttempt(r,'CVC',p.attempts.at(-1),{purpose:'entry_probe',groupId:'CVC',instanceId:'forced',promptFree:true,independentAccess:true,companionObserved:true});assert.equal(observation.result,'assisted');assert.equal(observation.reason,'target_help');});
 test('H13 repeated requests at level zero cannot erase previously recorded help',()=>{let p=R.launchFree(fresh(),pkg,KOT,{instanceId:'repeat'});p=E.requestHelp(p,pkg,{level:2});p=E.requestHelp(p,pkg,{level:0});assert.equal(p.activeInstance.helpLevel,2);assert(E.wasTargetPromptedThisVisit(p,'КОТ'));});
 test('H14 due review carries matching profile, launches, and genuinely reaches retention mastery',()=>{const p=dueReview(),before=structuredClone(p);const out=P.resolvePlacement(pkg,r,p,A,'CV2');assert.equal(out.kind,'engine_action');assert.equal(out.next.kind,'review');assert(out.profileToPersist);assert.equal(out.next.basedOnRevision,out.profileToPersist.revision);let saved=JSON.parse(JSON.stringify(out.profileToPersist));saved=R.launchAction(saved,pkg,out.next,{instanceId:'review-regression'});saved=R.answerAction(saved,pkg,{instanceId:'review-regression',response:exampleCorrectResponse(pkg.items[out.next.itemId])});assert.equal(saved.skillBasis['blend.cv'].status,'mastered');assert.deepEqual(p,before);});
 test('H15 original profile still rejects the review plan: stale-plan guard remains intact',()=>{const p=dueReview();const out=P.resolvePlacement(pkg,r,p,A,'CV2');assert.throws(()=>R.launchAction(p,pkg,out.next,{instanceId:'stale'}),/Stale or non-launchable route plan/);});
 test('H16 budget pause also returns the computed profile without issuing a fourth action',()=>{let p=entrySkill(fresh(),'blend.cv');p.currentVisit.budget=3;p.currentVisit.actions=3;const out=P.resolvePlacement(pkg,r,p,A,'CV2');assert.equal(out.kind,'engine_action');assert.equal(out.next.kind,'pause');assert(out.profileToPersist);assert.equal(out.profileToPersist.currentVisit.actions,3);assert.equal(out.profileToPersist.activeInstance,null);});
 test('H17 engine gate preserves the profile after reused evidence advances the cursor',()=>{let p=entrySkill(entrySkill(fresh(),'blend.cv'),'decode.cv_cv');const before=structuredClone(p);const out=P.resolvePlacement(pkg,r,p,A,'CV2');assert.equal(out.kind,'engine_gate');assert.equal(out.next.kind,'missing_skill');assert(out.profileToPersist);assert.equal(out.next.basedOnRevision,out.profileToPersist.revision);assert.deepEqual(R.nextAction(out.profileToPersist,pkg).action,out.next);assert.deepEqual(p,before);});
 test('H18 formal_route continues to return a launchable persisted profile',()=>{const p=entrySkill(fresh(),'blend.cv');const out=P.resolvePlacement(pkg,r,p,A,'CV2');assert.equal(out.kind,'formal_route');const launched=R.launchAction(JSON.parse(JSON.stringify(out.profileToPersist)),pkg,out.firstAction,{instanceId:'formal'});assert(launched.activeInstance||launched.programs[P.P1].activeInfo);});
 test('H19 unknown group is rejected in every public group-based decision function',()=>{const calls=[()=>P.selectProbe(r,fresh(),'FACT3'),()=>P.groupStatus(r,'FACT3'),()=>P.evaluateAttempt(r,'FACT3',{itemId:KOT},{}),()=>P.chooseGoal(r,A,'FACT3',{status:'pass'}),()=>P.practicePlan(pkg,r,'FACT3',A,'test'),()=>P.resolvePlacement(pkg,r,fresh(),A,'FACT3')];for(const call of calls)expectUnknown(call);});
 test('H20 invalid IDs are never completion, access recovery, or a practice default',()=>{for(const id of [undefined,'','__proto__','toString',{},false,7])expectUnknown(()=>P.resolvePlacement(pkg,r,fresh(),A,id));for(const a of [{...A,companionAvailable:false},{...A,skipAssessment:true},{...A,visualTextUsable:false}])expectUnknown(()=>P.resolvePlacement(pkg,r,fresh(),a,'FACT3'));});
 test('H21 FACTS3 remains valid and null is the explicit terminal successor',()=>{const next=P.resolvePlacement(pkg,r,fresh(),A,'FACTS3');assert.notEqual(next.kind,'scope_complete');const goal=P.chooseGoal(r,A,'TRANSFER',{status:'pass'});assert.equal(goal.groupId,null);const out=P.resolvePlacement(pkg,r,fresh(),A,goal.groupId);assert.equal(out.kind,'scope_complete');assert.equal(out.practice.entryRetestGroup,'STORY5');assert.equal(out.startNodeId,null);});
 test('H22 corrupted successor is rejected where chooseGoal emits it',()=>{const broken=structuredClone(r);broken.groups.CVC.successNextGroup='FACT3';expectUnknown(()=>P.chooseGoal(broken,A,'CVC',{status:'pass'}));});
 test('H23 upstream sequence card remains excluded; wrong order is not rescued by facts',()=>{assert(!r.groups.SEQ3.orderedItemIds.includes('task.1bb67acaeb41'));const row=r.groups.SEQ3.items[0],it=pkg.items[row.itemId];let p=R.launchFree(fresh(),pkg,it.id,{instanceId:'seq-wrong'}),response=exampleCorrectResponse(it);for(const id of row.questionIds){const q=it.answer.questions.find(q=>q.id===id);response.answers[id]=[q.options.find(o=>!q.correctOptionIds.includes(o.id)).id];}p=E.recordReadingStage(p,pkg,{instanceId:'seq-wrong',reading:response.reading});p=E.revealOptions(p,pkg);p=E.recordAttempt(p,pkg,{instanceId:'seq-wrong',response});const obs=P.evaluateAttempt(r,'SEQ3',p.attempts.at(-1),{purpose:'entry_probe',groupId:'SEQ3',instanceId:'seq-wrong',promptFree:true,independentAccess:true,freshPassageBeforeShow:true,companionObserved:true});assert.equal(obs.result,'fail');});
}
