import {createHash} from 'node:crypto';
import fs from 'node:fs';import assert from 'node:assert/strict';
import * as E from './engine.mjs';import * as R from './route.mjs';import {grade,exampleCorrectResponse} from './grading.mjs';import {stableShuffle} from './normalise.mjs';
const rawCurriculum=fs.readFileSync(new URL('./curriculum.json',import.meta.url));
const inputSha256=createHash('sha256').update(rawCurriculum).digest('hex');
const pkg=JSON.parse(rawCurriculum);
const results=[];let serial=0;
function test(name,fn){const start=Date.now();try{fn();results.push({name,status:'PASS',ms:Date.now()-start});}catch(e){results.push({name,status:'FAIL',error:e.stack,ms:Date.now()-start});console.error(name,e.message);}}
function ready(method='method_syllable_first'){
 let p=E.createProfile('test-only');p.knownLetters=[...'АБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯ'];p.availableCapabilities=Object.keys(pkg.capabilitySupports);p=E.switchProgram(p,method,pkg);return E.beginVisit(p,'v'+(++serial),{budget:30});}
function unlock(p,nid){for(const s of pkg.nodes[nid].prerequisiteSkills)p=E.confirmEntrySkill(p,pkg,s,{verifier:'companion',reason:'SYNTHETIC TEST FIXTURE'});return p;}
function newVisit(p){return E.beginVisit(E.endVisit(p),'v'+(++serial),{budget:30});}
function launch(p,nid,{itemId,phase='independent',mode}={}){p=unlock(p,nid);itemId??=E.selectCheck(pkg,nid,p).itemId;return E.presentTask(p,pkg,{instanceId:'t'+(++serial),itemId,nodeId:nid,phase,mode});}
function answer(p,raw){return E.recordAttempt(p,pkg,{instanceId:p.activeInstance.instanceId,response:raw??exampleCorrectResponse(pkg.items[p.activeInstance.itemId])});}
function earn(p,nid){for(let i=0;i<2;i++){p=newVisit(p);p=answer(launch(p,nid));}p=answer(launch(p,nid,{phase:'application',itemId:pkg.nodes[nid].applicationId}));p=E.updateNodeEvidence(p,pkg,nid);return p;}

test('All authored answer contracts accept the exact raw key',()=>{for(const t of Object.values(pkg.items))assert.equal(grade(t,exampleCorrectResponse(t)).outcome,'correct',t.id);});
test('All incorrect single choices rejected',()=>{for(const t of Object.values(pkg.items).filter(t=>t.answer.kind==='choice'))for(const o of t.options)if(!t.answer.correctOptionIds.includes(o.id))assert.notEqual(grade(t,{optionIds:[o.id],reading:{verifier:'companion',correct:true}}).outcome,'correct',t.id);});
test('Each paragraph question rejects a wrong option separately',()=>{for(const t of Object.values(pkg.items).filter(t=>t.kind==='passage'))for(const q of t.answer.questions){const bad=q.options.find(o=>!q.correctOptionIds.includes(o.id));if(bad){const r=exampleCorrectResponse(t);r.answers[q.id]=[bad.id];assert.equal(grade(t,r).outcome,'incorrect',t.id);}}});
test('Incomplete question set is partial, not correct',()=>{const t=Object.values(pkg.items).find(t=>t.answer.questions?.length>1);const r=exampleCorrectResponse(t);delete r.answers[t.answer.questions[1].id];assert.equal(grade(t,r).outcome,'partial');});
test('Empty question set cannot create successful evidence',()=>{let p=launch(ready(),'p1.H01');p=answer(p,{answers:{}});assert(p.activeInstance);assert.equal(p.attempts.length,0);assert.equal(E.nodeEvidenceStatus(p,pkg,'p1.H01').status,'learning');});
test('Partial answers save, export/import, then merge into complete record',()=>{let p=launch(ready(),'p1.H01');const t=pkg.items[p.activeInstance.itemId],id=p.activeInstance.instanceId;const qs=t.answer.questions;assert(qs.length>1);p=answer(p,{answers:{[qs[0].id]:qs[0].correctOptionIds},reading:{verifier:'companion',correct:true}});assert(p.activeInstance.lastPartial);assert.equal(p.receipts[id],undefined);p=E.importProfile(E.exportProfile(p),pkg);p=answer(p,{answers:Object.fromEntries(qs.slice(1).map(q=>[q.id,q.correctOptionIds]))});assert.equal(p.receipts[id].outcome,'correct');assert.equal(p.attempts[0].readingVerified,true);});
test('Protected item/node/program identity cannot be overwritten by response',()=>{const p=launch(ready(),'p1.C01');for(const k of ['nodeId','itemId','programId','contentHash','freshAtPresentation','independent','questionResults'])assert.throws(()=>E.recordAttempt(p,pkg,{instanceId:p.activeInstance.instanceId,response:exampleCorrectResponse(pkg.items[p.activeInstance.itemId]),[k]:'forged'}));});
test('Claimed correct without raw input is rejected',()=>{const p=launch(ready(),'p1.C01');assert.throws(()=>E.recordAttempt(p,pkg,{instanceId:p.activeInstance.instanceId,outcome:'correct'}));});
test('Claimed correct cannot override a wrong raw answer',()=>{const p=launch(ready(),'p1.B01');assert.throws(()=>E.recordAttempt(p,pkg,{instanceId:p.activeInstance.instanceId,outcome:'correct',response:{optionIds:['wrong']}}));});
test('Existing item outside node cannot be launched as its check',()=>{const p=unlock(ready(),'p1.C01');assert.throws(()=>E.presentTask(p,pkg,{instanceId:'foreign',nodeId:'p1.C01',itemId:pkg.nodes['p1.H01'].checkIds[0],phase:'independent'}));});
test('Training record cannot be launched as reserved check',()=>{const p=unlock(ready(),'p1.C01');assert.throws(()=>E.presentTask(p,pkg,{instanceId:'wrongphase',nodeId:'p1.C01',itemId:pkg.nodes['p1.C01'].trainingIds[0],phase:'independent'}));});
test('Missing prerequisite skill blocks a check before any exposure',()=>{const p=ready();const id=pkg.nodes['p1.C01'].checkIds[0];assert.throws(()=>E.presentTask(p,pkg,{instanceId:'missing',nodeId:'p1.C01',itemId:id,phase:'independent'}));assert(!p.exposures.itemIds.includes(id));});
test('Missing letter cannot be bypassed with a favorite interest',()=>{let p=unlock(ready(),'p1.C01');p.knownLetters=[];p.interests=['videogames'];assert.equal(E.selectCheck(pkg,'p1.C01',p).reason,'MISSING_CAPABILITY');});
test('No broad vowel capability unlocks initial Ё from И',()=>{const p=ready();p.availableCapabilities=['vowel.i.after_consonant'];const t=Object.values(pkg.items).find(t=>t.learnerText==='ЁЖ');assert(t);assert(!E.isEligible(t,p));assert(E.missingCapabilities(t,p).capabilities.includes('vowel.ё.initial'));});
test('Initial, internal and final clusters are independent flags',()=>{let p=ready();p.availableCapabilities=['cluster.initial.2'];const t=Object.values(pkg.items).find(t=>t.learnerText==='СУМКА');assert(!E.isEligible(t,p));});
test('Boundary selection cannot be answered with assembled syllable tokens',()=>{const t=pkg.items[pkg.nodes['p2.P04'].checkIds[0]];assert.equal(t.kind,'boundary');assert.equal(grade(t,{tokenIds:['t0','t1']}).outcome,'incorrect');assert.equal(grade(t,{boundaries:t.answer.acceptedBoundaries[0]}).outcome,'correct');});
test('One МА token cannot be reused as two tokens',()=>{const t=Object.values(pkg.items).find(t=>t.kind==='compose'&&t.learnerText==='МАМА');assert.equal(grade(t,{tokenIds:['t0','t0']}).outcome,'incorrect');assert.equal(grade(t,{tokenIds:['t1','t0']}).outcome,'correct');});
test('Phrase composition preserves spaces between words',()=>{const t=Object.values(pkg.items).find(t=>t.kind==='compose'&&t.learnerText==='ТУТ ЛИПА');assert.equal(grade(t,exampleCorrectResponse(t)).outcome,'correct');});
test('All transformations match their authored operations',()=>{for(const t of Object.values(pkg.items).filter(t=>t.kind==='transform'))assert.equal(E.applyTransform(t),t.resultText,t.id);});
test('ЛИПА→ПИЛА is a letter permutation, not swapping ЛИ and ПА',()=>{const t=Object.values(pkg.items).find(t=>t.learnerText==='ЛИПА'&&t.resultText==='ПИЛА');assert.equal(t.operation.kind,'reorder_letters');assert.equal(E.applyTransform(t),'ПИЛА');});
test('P2 three-fact prerequisite is taught before that node',()=>{const path=pkg.programs[1].defaultPath;assert(path.indexOf('p2.R02')<path.indexOf('p2.R01'));assert(path.indexOf('p2.BR04')<path.indexOf('p2.R03'));assert(path.indexOf('p2.BR05')<path.indexOf('p2.R04'));});
test('P2 internal and initial cluster bridges appear before phrase location',()=>{const path=pkg.programs[1].defaultPath;assert(path.indexOf('p2.BR01')<path.indexOf('p2.S03'));assert(path.indexOf('p2.BR02')<path.indexOf('p2.S03'));});
test('Q03 is an explicit review, not duplicate mandatory progression',()=>{assert.equal(pkg.nodes['p2.Q03'].nodeRole,'review');assert(!pkg.programs[1].defaultPath.includes('p2.Q03'));});
test('All reserved sequence/cause checks contain a matching question skill',()=>{for(const n of Object.values(pkg.nodes).filter(n=>['text.sequence2','text.sequence3','text.cause','text.cause3'].includes(n.skillId)))for(const id of n.checkIds)assert(pkg.items[id].answer.questions.some(q=>q.skillIds.includes(n.skillId)),id);});
test('Ambiguous disk contradiction is made explicit',()=>{assert(pkg.items['task.dac0e49f7310'].learnerText.includes('На столе диска нет'));});
test('Onion meaning is established by preparing food, not proximity alone',()=>{const t=pkg.items['task.062a207842d5'];assert(t.learnerText.includes('нарезал лук'));assert(t.learnerText.includes('салат'));});
test('Verb meaning does not offer the same word as its correct definition',()=>{const set=pkg.taskSets.whole_action;for(const id of [...set.trainingIds,...set.checkIds]){const t=pkg.items[id];const val=t.options.find(x=>t.answer.correctOptionIds.includes(x.id)).text;assert.notEqual(E.normalise(t.learnerText),E.normalise(val));}});
test('Analysis application is not called a test of word meaning',()=>{assert.equal(pkg.nodes['p1.A01'].applicationKind,'analysis_application');assert.equal(pkg.nodes['p1.A02'].applicationKind,'analysis_application');});
test('AK/AR classified as new sequences, not new meaningful words',()=>{assert.equal(pkg.taskSets.vc.freshness,'stimulus_unseen');for(const id of pkg.taskSets.vc.checkIds)assert.equal(pkg.items[id].evidenceType,'decoding_sequence');});
test('Cat sleeping no longer claims a games topic',()=>{assert(!pkg.items['task.e5874fcf2645'].interestTags.includes('videogames'));});
test('Onion soup no longer claims a technology topic',()=>{assert(!pkg.items['task.5b71a1341219'].interestTags.includes('technology'));});
test('Early complex D02/D04 are listener uses, not globally audio-only texts',()=>{for(const n of ['p1.D02','p1.D04']){assert.equal(pkg.nodes[n].routeMode,'listen');for(const id of pkg.nodes[n].trainingIds){const t=pkg.items[id];assert(t.allowedModes.includes('read'));assert(t.freeTrainerVisible);assert(!('textReadMode'in t));}}});
test('Free trainer can open a difficult text even with no known letters',()=>{let p=ready();p.knownLetters=[];p.availableCapabilities=[];const t=pkg.nodes['p1.D02'].trainingIds[2];p=R.launchFree(p,pkg,t,{mode:'read'});assert.equal(p.activeInstance.mode,'read');assert.equal(p.activeInstance.context,'free');assert.equal(p.activeInstance.eligibleAtPresentation,false);});
test('Listening earns meaning evidence, not verified reading',()=>{let p=launch(ready(),'p1.D02',{mode:'listen'});p=answer(p);assert.equal(p.attempts[0].readingVerified,false);assert.equal(p.attempts[0].decodingTransfer,false);});
test('A heard story is not a brand-new comprehension passage later',()=>{const t=pkg.items[pkg.nodes['p1.H01'].checkIds[0]];let p=E.commitExposure(ready(),{heardPassages:[t.learnerText]});assert.equal(E.isFresh(t,pkg.taskSets.three_facts,p),false);});
test('Free selection changes global exposure but not route position or mastery',()=>{let p=ready();const before=JSON.stringify(p.programs);p=R.launchFree(p,pkg,pkg.nodes['p1.C01'].checkIds[0],{});p=answer(p);assert.equal(JSON.stringify(p.programs),before);assert.equal(p.confirmedSkills.length,0);assert.equal(p.exposures.itemIds.length,1);});
test('Same written word is not new after changing programme or case',()=>{let p=E.commitExposure(ready(),{texts:['лама']});p=E.switchProgram(p,'method_word_first',pkg);const t=pkg.items[pkg.nodes['p1.C01'].checkIds[0]];assert(!E.isFresh(t,pkg.taskSets.two_cv,p));});
test('A target-audio request disqualifies independent reading',()=>{let p=launch(ready(),'p1.C01');p=E.requestHelp(p,pkg,{level:4,targetAudio:true});p=answer(p);assert.equal(p.attempts[0].independent,false);assert.equal(p.attempts[0].decodingTransfer,false);});
test('An explicit definition hint is recorded at its authored high support level',()=>{let p=launch(ready(),'p1.D01');const t=pkg.items[p.activeInstance.itemId];p=E.applyHint(p,pkg,0);assert.equal(p.activeInstance.helpLevel,t.hintLevels?.[0]??1);});
test('ASR alone never confirms a reading attempt',()=>{let p=launch(ready(),'p1.C01');p=answer(p,{reading:{verifier:'ASR',correct:true}});assert.equal(p.attempts[0].outcome,'uncertain');assert.equal(p.attempts[0].readingVerified,false);});
test('Correct choice without reading cannot finish read_meaning',()=>{let p=launch(ready('method_word_first'),'p2.N05');const t=pkg.items[p.activeInstance.itemId];p=answer(p,{optionIds:t.answer.correctOptionIds});assert.equal(p.attempts[0].outcome,'uncertain');assert.equal(E.nodeEvidenceStatus(p,pkg,'p2.N05').status,'learning');});
test('Meaning options stay hidden until read_meaning reading stage is recorded',()=>{let p=launch(ready('method_word_first'),'p2.N05');assert.throws(()=>E.revealOptions(p,pkg));p=E.recordReadingStage(p,pkg,{instanceId:p.activeInstance.instanceId,reading:{verifier:'companion',correct:true}});p=E.revealOptions(p,pkg);assert(p.activeInstance.optionsRevealed);});
test('Revealed distractors consume written exposure too',()=>{let p=launch(ready(),'p1.B01');const opts=pkg.items[p.activeInstance.itemId].options;p=E.revealOptions(p,pkg);for(const x of opts)assert(p.exposures.stimuli.includes(E.normalise(x.text)));});
test('Stable option permutation survives export/import and resume',()=>{let p=launch(ready(),'p1.B01');const a=cp(p.activeInstance);p=E.importProfile(E.exportProfile(p),pkg);assert.deepEqual(p.activeInstance.optionOrder,a.optionOrder);p=E.presentTask(p,pkg,{instanceId:a.instanceId,itemId:a.itemId,nodeId:a.nodeId,phase:a.phase});assert.deepEqual(p.activeInstance.optionOrder,a.optionOrder);});
test('Shuffle is not permanently correct-first across instances',()=>{const orders=new Set(Array.from({length:30},(_,i)=>stableShuffle(['o1','o2','o3'],'x'+i).join()));assert(orders.size>1);});
test('Two independent visits plus application gives pending retention, not full mastery',()=>{const p=earn(ready(),'p1.C01');assert.equal(E.nodeEvidenceStatus(p,pkg,'p1.C01').status,'pending_retention');assert(!p.confirmedSkills.includes('decode.cv_cv'));assert(E.hasSkill(p,pkg,'decode.cv_cv'));});
test('Delayed retention is required before mastered',()=>{let p=earn(ready(),'p1.C01');for(let i=0;i<3;i++)p=newVisit(p);const r=p.reviewQueue.find(x=>x.nodeId==='p1.C01');p=answer(launch(p,'p1.C01',{itemId:r.itemId,phase:'review'}));p=E.updateNodeEvidence(p,pkg,'p1.C01');assert.equal(E.nodeEvidenceStatus(p,pkg,'p1.C01').status,'mastered');});
test('Known-word fading does not imply new-word decoding',()=>{let p=earn(ready('method_word_first'),'p2.P05');assert.equal(E.hasSkill(p,pkg,'decode.cv_cv'),false);assert.equal(p.skillBasis['decode.remove_hint'].novelDecodingVerified,false);});
test('Duplicate answer submission is idempotent',()=>{let p=launch(ready(),'p1.C01');const r={instanceId:p.activeInstance.instanceId,response:exampleCorrectResponse(pkg.items[p.activeInstance.itemId])};p=E.recordAttempt(p,pkg,r);const q=E.recordAttempt(p,pkg,r);assert.equal(q.attempts.length,p.attempts.length);assert.equal(q.revision,p.revision);});
test('Programme switching restores unfinished active task and freshness',()=>{let p=launch(ready(),'p1.C01');const a=cp(p.activeInstance);p=E.switchProgram(p,'method_word_first',pkg);assert.equal(p.activeInstance,null);p=E.switchProgram(p,'method_syllable_first',pkg);assert.deepEqual(p.activeInstance,a);});
test('An answered suspended task does not resurrect',()=>{let p=launch(ready(),'p1.C01');p=answer(p);p=E.switchProgram(p,'method_word_first',pkg);p=E.switchProgram(p,'method_syllable_first',pkg);assert.equal(p.activeInstance,null);});
test('Thin or malformed imported profile is rejected',()=>{for(const p of [{schemaVersion:2,programs:{},exposures:{}},{...ready(),knownLetters:'ALL'},{...ready(),confirmedSkills:['fake.universal']},{...ready(),exposures:{}}])assert.throws(()=>E.importProfile(JSON.stringify(p),pkg));});
test('V1 migration keeps all original history and does not grant all vowel functions',()=>{const old={schemaVersion:1,id:'x',knownLetters:['М','И'],availablePatterns:['vowel_functions'],programs:{},exposures:{words:['МИР']},notes:'keep'};const p=E.migrateV1(old,pkg);assert.deepEqual(p.legacyPractice[0].originalProfile,old);assert.deepEqual(p.availableCapabilities,[]);assert(p.exposures.words.includes('МИР'));assert.deepEqual(E.validateProfile(p,pkg),[]);});
test('Third program can be registered without hardcoded one/two engine branch',()=>{const pp=cp(pkg);const third=cp(pp.programs[0]);third.id='adult_demo';third.nodeIds=[];third.defaultPath=[];pp.programs.push(third);let p=E.switchProgram(E.createProfile(),third.id,pp);assert.equal(p.currentProgramId,third.id);});
test('Demonstrations have different concrete action order on same target ЛУПА',()=>{const a=R.demoSteps(pkg,'p1'),b=R.demoSteps(pkg,'p2');assert.equal(a.steps[0].action,'show_chunks');assert.equal(b.steps[0].action,'meaning_anchor');assert(b.steps.some(s=>pkg.items[s.itemId]?.kind==='find_part'));assert(b.steps.some(s=>pkg.items[s.itemId]?.kind==='transform'));assert.notDeepEqual(a.steps.map(s=>s.action),b.steps.map(s=>s.action));});
test('All episode words used as meaning anchors have real definitions',()=>{for(const ep of Object.values(pkg.episodes))for(const s of ep.steps)if(s.action==='meaning_anchor')assert(s.spokenText&&pkg.vocabulary[s.meaningKey],s.id);});
test('Both demonstrations preserve the P05 delayed-known reserve',()=>{let p=ready('method_word_first');for(const m of ['p1','p2']){const ep=R.demoSteps(pkg,m);for(const s of ep.steps){const it=pkg.items[s.itemId];p=E.commitExposure(p,{texts:[s.visibleText??'',...(s.parts??[]),...(s.chunks??[]),it?.learnerText??'',it?.resultText??''],promptedTexts:s.promptLevel>=2?[s.visibleText??it?.learnerText??'']:[]});}}p=newVisit(p);p=unlock(p,'p2.P05');assert(E.checkInventory(pkg,'p2.P05',p).filter(x=>x.eligible&&x.fresh).length>=2);});
test('All four old demo words can be reused as familiar fading on another visit, not as new words',()=>{let p=E.commitExposure(ready('method_word_first'),{texts:['ЛАМА','ЛАПА','НОРА','КОСА'],promptedTexts:['ЛАМА','ЛАПА','НОРА','КОСА']});p=newVisit(p);p=unlock(p,'p2.P05');assert.equal(E.selectCheck(pkg,'p2.P05',p).kind,'task');assert.equal(E.isFresh(pkg.items[pkg.nodes['p1.C01'].checkIds[0]],pkg.taskSets.two_cv,p),false);});
test('Finite-bank exhaustion reports unassessed, never invented mastery',()=>{let p=unlock(ready(),'p1.C01');for(const x of E.checkInventory(pkg,'p1.C01',p))p=E.commitExposure(p,{texts:[pkg.items[x.itemId].learnerText],itemIds:[x.itemId]});assert.equal(E.selectCheck(pkg,'p1.C01',p).reason,'NO_UNSEEN_CANDIDATE');assert.equal(E.nodeEvidenceStatus(p,pkg,'p1.C01').status,'learning');});
test('Route budget counts model screens and resumes the exact next step',()=>{let p=ready();p=unlock(p,'p1.C01');p=R.chooseEntry(p,pkg,'p1.C01');p.currentVisit.budget=1;let z=R.nextAction(p,pkg);p=R.launchAction(z.profile,pkg,z.action);assert.equal(p.currentVisit.actions,1);p=R.acknowledgeInfo(p,pkg,p.programs[p.currentProgramId].activeInfo.planId);assert.equal(R.nextAction(p,pkg).action.kind,'pause');p=newVisit(p);z=R.nextAction(p,pkg);assert.equal(z.action.stepId,pkg.episodes[pkg.nodes['p1.C01'].episodeIds[0]].steps[1].id);});
test('Stale route plan cannot launch after profile revision changed',()=>{let p=unlock(ready(),'p1.C01');p=R.chooseEntry(p,pkg,'p1.C01');const z=R.nextAction(p,pkg);p=E.commitExposure(z.profile,{texts:['не связано']});assert.throws(()=>R.launchAction(p,pkg,z.action));});

test('Fine capability cannot be confirmed from listed IDs without performed checks',()=>{const p=ready();const k='vowel.ё.initial';assert.throws(()=>E.confirmCapability(p,pkg,k,{verifier:'companion',observedItemIds:pkg.capabilitySupports[k].checkIds,reason:'manual ids only'}));});
test('Two actual target-function checks confirm only that function, never reading whole words',()=>{let p=ready();p.availableCapabilities=[];const key='vowel.ё.initial';const ids=pkg.capabilitySupports[key].checkIds;for(const id of ids){p=E.presentTask(p,pkg,{instanceId:'cap'+(++serial),itemId:id,context:'support',phase:'support',mode:'shared',supportCapability:key});p=answer(p);assert.equal(p.attempts.at(-1).readingVerified,false);}p=E.confirmCapability(p,pkg,key,{verifier:'companion',observedItemIds:ids,reason:'Only initial Ё checked, remaining parts supported.'});assert.deepEqual(p.availableCapabilities,[key]);assert(!p.confirmedSkills.includes('decode.cv_cv'));});
test('Function check with target help cannot be silently marked mastered',()=>{let p=ready();const key='sign.soft',id=pkg.capabilitySupports[key].checkIds[0];p=E.presentTask(p,pkg,{instanceId:'caphelp',itemId:id,context:'support',phase:'support',mode:'shared',supportCapability:key});p=E.requestHelp(p,pkg,{level:4});p=answer(p);assert.equal(p.attempts.at(-1).functionVerified,false);});
test('Only target-mode reading records are accepted by the independent route',()=>{const p=unlock(ready(),'p1.C01');assert.throws(()=>E.presentTask(p,pkg,{instanceId:'mode-mismatch',itemId:pkg.nodes['p1.C01'].checkIds[0],nodeId:'p1.C01',phase:'independent',mode:'listen'}));});
test('Manual practice-only continuation does not manufacture prerequisite skills',()=>{let p=unlock(ready(),'p1.C01');p=R.chooseEntry(p,pkg,'p1.C01');const before=[...p.confirmedSkills];p=R.continuePracticeOnly(p,pkg,{nodeId:'p1.C01',verifier:'companion',reason:'No fresh candidates; continue supported practice only'});assert.deepEqual(p.confirmedSkills,before);assert.equal(p.programs[p.currentProgramId].practiceOnly,true);assert.throws(()=>E.presentTask(p,pkg,{instanceId:'false-check',itemId:pkg.nodes['p1.A04'].checkIds[0],nodeId:'p1.A04',phase:'independent'}));});
test('Real early tech words retain the CV-CV structure',()=>{for(const word of ['КОДЫ','БОТЫ','МОДЫ','ФОТО']){const t=pkg.nodes['p1.C01'].trainingIds.map(id=>pkg.items[id]).find(t=>t.learnerText===word);assert(t);assert.equal(t.parts.length,2);assert(t.parts.every(x=>x.length===2));assert(t.interestTags.some(x=>['videogames','technology','phones'].includes(x)));}});
test('Preferred game/tech theme selects an actual thematic training episode',()=>{let p=unlock(ready(),'p1.C01');p.interests=['videogames'];p=R.chooseEntry(p,pkg,'p1.C01');const z=R.nextAction(p,pkg);assert.equal(z.action.kind,'episode_info');const episode=pkg.episodes[z.action.episodeId];assert(episode.steps.some(s=>['БОТЫ','МОДЫ'].includes(pkg.items[s.itemId]?.learnerText)));});
test('Incorrect application is available to retry and is not treated as done',()=>{let p=unlock(ready(),'p1.C01');p=R.chooseEntry(p,pkg,'p1.C01');const state=p.programs[p.currentProgramId];state.episodeIndex=2;state.appDone=false;p.currentVisit.checkedNodes=['p1.C01'];const z=R.nextAction(p,pkg);assert.equal(z.action.kind,'application');p=R.launchAction(z.profile,pkg,z.action);p=R.answerAction(p,pkg,{instanceId:p.activeInstance.instanceId,response:{optionIds:['wrong']}});assert.equal(p.programs[p.currentProgramId].appDone,false);assert.equal(R.nextAction(p,pkg).action.kind,'application');});
test('Legacy model item now always belongs to current training bank',()=>{for(const ts of Object.values(pkg.taskSets))assert(ts.trainingIds.includes(ts.modelItemId),ts.id);});
function cp(x){return structuredClone(x)}
fs.writeFileSync(new URL('../reports/runtime_tests.json',import.meta.url),JSON.stringify({inputSha256,version:pkg.contentVersion,passed:results.filter(x=>x.status==='PASS').length,failed:results.filter(x=>x.status==='FAIL').length,tests:results},null,2));
console.log(JSON.stringify({passed:results.filter(x=>x.status==='PASS').length,failed:results.filter(x=>x.status==='FAIL').length}));
if(results.some(x=>x.status==='FAIL'))process.exitCode=1;
