'use client';
import {useEffect,useRef,useState} from 'react';
import {BookOpen,Volume2,Mic,MicOff,ArrowRight,Settings2,Leaf,Keyboard,Image as ImageIcon,Star,Pause,Play,Check,RotateCcw,HelpCircle,Home as HomeIcon,Download} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Switch} from '@/components/ui/switch';
import {Progress} from '@/components/ui/progress';
import {Select,SelectTrigger,SelectContent,SelectItem,SelectValue} from '@/components/ui/select';
import {levels,pictures,breaks,normalize,checkTyped,checkSpeech} from '@/lib/learning';
import RestHub from '@/components/rest-hub';
import PictureScene from '@/components/picture-scene';
import {wordPool,makeDeck,pictureAnswer} from '@/lib/session';
import {SlowReadingAttempt} from '@/lib/slow-reading';
import {findTypo,type TypoHint} from '@/lib/typo';
import {classifyUtterance} from '@/lib/feedback';
import {startLocalSpeech} from '@/lib/local-speech';

type Stage='letters'|'syllables'|'words'|'pictures';
type Mode='read'|'fly'|'type';
type Feedback={kind:'neutral'|'success'|'uncertain'|'error';text:string};
type Settings={unit:number;length:number;motion:boolean;sound:boolean;autoSpeech:boolean;slow:boolean;color:boolean;micConsent:boolean;micDevice:string};
type Entry={at:string;target:string;stage:Stage;mode:Mode;result:string;via:string};
const defaults:Settings={unit:0,length:5,motion:true,sound:true,autoSpeech:false,slow:true,color:true,micConsent:false,micDevice:''};
const stages:{id:Stage;name:string;title:string}[]=[{id:'letters',name:'Буквы',title:'Знакомимся с буквами'},{id:'syllables',name:'Слоги',title:'Соединяем звуки'},{id:'words',name:'Слова',title:'Читаем целое слово'},{id:'pictures',name:'Картинки',title:'От картинки к слову'}];
const names:Record<string,string>={Б:'БЭ',В:'ВЭ',Г:'ГЭ',Д:'ДЭ',Ж:'ЖЭ',З:'ЗЭ',К:'КА',Л:'ЭЛЬ',М:'ЭМ',Н:'ЭН',П:'ПЭ',Р:'ЭР',С:'ЭС',Т:'ТЭ',Ф:'ЭФ',Х:'ХА',Ц:'ЦЭ',Ч:'ЧЕ',Ш:'ША',Щ:'ЩА',Й:'И КРАТКОЕ',Ь:'МЯГКИЙ ЗНАК',Ъ:'ТВЁРДЫЙ ЗНАК'};
export default function Home(){
 const [stage,setStage]=useState<Stage>('syllables'),[mode,setMode]=useState<Mode>('read'),[settings,setSettings]=useState(defaults),[ready,setReady]=useState(false),[storageWarning,setStorageWarning]=useState('');
 const [index,setIndex]=useState(0),[count,setCount]=useState(0),[stars,setStars]=useState(0),[history,setHistory]=useState<Entry[]>([]),[answer,setAnswer]=useState(''),[feedback,setFeedback]=useState<Feedback>({kind:'neutral',text:'Не спеши. У тебя получится.'});
 const [parent,setParent]=useState(false),[paused,setPaused]=useState(false),[rest,setRest]=useState(false),[done,setDone]=useState(false),[restIndex,setRestIndex]=useState(0),[hint,setHint]=useState(false),[listening,setListening]=useState(false),[supported,setSupported]=useState(false),[consent,setConsent]=useState(false),[heard,setHeard]=useState(''),[speaking,setSpeaking]=useState(false);
 const [loadingSpeech,setLoadingSpeech]=useState(false),[micLevel,setMicLevel]=useState(0),[micDevices,setMicDevices]=useState<MediaDeviceInfo[]>([]),[micTesting,setMicTesting]=useState(false),[micMessage,setMicMessage]=useState('Выбери микрофон и проверь: полоска должна двигаться, когда ты говоришь.');
 const [lessonMic,setLessonMic]=useState(false),[cooldown,setCooldown]=useState(false),[mistakes,setMistakes]=useState(0),[spectrum,setSpectrum]=useState<number[]>(Array(12).fill(0));
 const [flyCards,setFlyCards]=useState<{id:number;text:string;caught:boolean}[]>([]),[flyInputStatus,setFlyInputStatus]=useState('');const flyNext=useRef(3),caughtIds=useRef(new Set<number>());
 const resultSink=useRef<(r:any)=>void>(()=>{}),helpLock=useRef(false),speechEpoch=useRef(0);
 const input=useRef<HTMLInputElement>(null),recognition=useRef<any>(null),epoch=useRef(0),awarded=useRef(false),timer=useRef<ReturnType<typeof setTimeout>|null>(null),mounted=useRef(true);
 const slowAttempt=useRef(new SlowReadingAttempt());const [speechProgress,setSpeechProgress]=useState(0),[attemptStatus,setAttemptStatus]=useState('');const activitySink=useRef<(phase:'sound'|'pause')=>void>(()=>{});
 const [typo,setTypo]=useState<TypoHint|null>(null);
 const [deck,setDeck]=useState<string[]>([]),[session,setSession]=useState(0),[scene,setScene]=useState(false);
 const pool=stage==='pictures'?pictures.map(x=>x.word):stage==='words'?wordPool(settings.unit):levels[settings.unit][stage];
 const target=deck[index%Math.max(1,deck.length)]||pool[0],picture=stage==='pictures'?pictures.find(p=>p.word===target)??null:null;
 useEffect(()=>{if(ready)setDeck(old=>makeDeck(pool,Math.max(24,settings.length),old))},[ready,stage,mode,settings.unit,session]);
 const task=stage==='pictures'?'Напиши, что на картинке':mode==='read'?(stage==='letters'?'Прочитай букву вслух':stage==='syllables'?'Прочитай слог вслух':'Прочитай слово вслух'):mode==='fly'?'Поймай: напечатай любой и нажми Enter':stage==='letters'?'Напечатай букву':stage==='syllables'?'Напечатай слог':'Напечатай слово';
 function stop(){slowAttempt.current.reset();setSpeechProgress(0);setAttemptStatus('');epoch.current++;speechEpoch.current++;helpLock.current=false;setCooldown(false);setSpectrum(Array(12).fill(0));if(timer.current)clearTimeout(timer.current);try{recognition.current?.abort()}catch{}recognition.current=null;setListening(false);setLoadingSpeech(false);setMicLevel(0);setMicTesting(false);if(typeof window!=='undefined'&&'speechSynthesis'in window)window.speechSynthesis.cancel();setSpeaking(false)}
 function resetCard(){setTypo(null);setScene(false);stop();awarded.current=false;setAnswer('');setHint(false);setHeard('');setMistakes(0);setFeedback({kind:'neutral',text:'Не спеши. У тебя получится.'})}
 function navigate(s:Stage,m:Mode=mode){setSession(n=>n+1);setFlyInputStatus('');setLessonMic(false);resetCard();setStage(s);setMode(s==='pictures'?'type':m);setCount(0);setIndex(0);setDone(false);setRest(false);setPaused(false)}
 useEffect(()=>{mounted.current=true;setSupported(Boolean(typeof navigator.mediaDevices?.getUserMedia==='function'&&typeof window.AudioContext==='function'&&typeof window.WebAssembly==='object'));void navigator.mediaDevices?.enumerateDevices().then(d=>setMicDevices(d.filter(x=>x.kind==='audioinput'))).catch(()=>{});try{const raw=JSON.parse(localStorage.getItem('reading-steps-v3')||'null');if(raw){const s=raw.settings||{};setSettings({...defaults,...Object.fromEntries(Object.keys(defaults).filter(k=>typeof s[k]===typeof defaults[k as keyof Settings]).map(k=>[k,s[k]])),unit:Number.isInteger(s.unit)&&s.unit>=0&&s.unit<levels.length?s.unit:0,length:[3,5,8].includes(s.length)?s.length:5});if(Number.isInteger(raw.stars)&&raw.stars>=0)setStars(raw.stars);if(Array.isArray(raw.history))setHistory(raw.history.filter((e:any)=>e&&typeof e.target==='string'&&typeof e.at==='string').slice(-300))}}catch{setStorageWarning('Сохранение недоступно. Можно заниматься, но результаты останутся только до закрытия страницы.')}setReady(true);return()=>{mounted.current=false;epoch.current++;try{recognition.current?.abort()}catch{}if(timer.current)clearTimeout(timer.current);window.speechSynthesis?.cancel()}},[]);
 useEffect(()=>{if(!ready)return;try{localStorage.setItem('reading-steps-v3',JSON.stringify({settings,stars,history}))}catch{setStorageWarning('Не удалось сохранить результаты на этом устройстве.')}},[settings,stars,history,ready]);
 useEffect(()=>{function hide(){if(document.hidden){stop();setPaused(true)}}document.addEventListener('visibilitychange',hide);return()=>document.removeEventListener('visibilitychange',hide)},[]);
 useEffect(()=>{if(!parent&&!paused&&!rest&&!done&&mode!=='read')input.current?.focus()},[index,mode,parent,paused,rest,done,stage]);
 function record(result:string,via:string){setHistory(h=>[...h,{at:new Date().toISOString(),target,stage,mode,result,via}].slice(-300))}
 function success(via:string){setTypo(null);if(awarded.current)return;awarded.current=true;recognition.current?.setEnabled?.(false);setFeedback({kind:'success',text:`Верно! ${target}. Получилось!`});setHeard('');setStars(n=>n+1);record('success',via);if(mode==='read'&&settings.sound&&settings.autoSpeech)speak(`Верно! ${target.toLowerCase()}.`)}
 function releaseSoon(delay=650){if(timer.current)clearTimeout(timer.current);const token=epoch.current;timer.current=setTimeout(()=>{if(epoch.current!==token)return;helpLock.current=false;setCooldown(false)},delay)}
 function speak(text:string){setCooldown(true);recognition.current?.setEnabled?.(false);speechEpoch.current++;const token=speechEpoch.current;if(!settings.sound){releaseSoon();return}if(!('speechSynthesis'in window)){releaseSoon();return}speechSynthesis.cancel();const voices=speechSynthesis.getVoices(),voice=voices.find(v=>v.lang.toLowerCase().startsWith('ru'));if(voices.length&&!voice){releaseSoon();return}const u=new SpeechSynthesisUtterance(text);u.lang='ru-RU';if(voice)u.voice=voice;u.rate=settings.slow?.72:.9;setSpeaking(true);u.onend=u.onerror=()=>{if(speechEpoch.current!==token)return;setSpeaking(false);setCooldown(true);releaseSoon(450)};speechSynthesis.speak(u)}
 function wrongResponse(value:string,via:string){if(awarded.current||helpLock.current)return;helpLock.current=true;recognition.current?.setEnabled?.(false);setCooldown(true);const attempt=mistakes+1;setMistakes(attempt);setHeard(value);setHint(true);record('retry',via);const prompt=attempt===1?`Здесь ${target}. Начни с первой буквы.`:attempt===2?`Давай вместе: ${target}. Послушай и повтори.`:`Сначала найди ${target}. Потом прочитай.`;setFeedback({kind:'error',text:prompt});if(settings.sound&&settings.autoSpeech&&mode==='read')speak(attempt===1?`Здесь ${target.toLowerCase()}. Попробуй ещё раз.`:attempt===2?`Послушай. ${target.toLowerCase()}. Теперь ты.`:`Найди такой же слог. ${target.toLowerCase()}.`);else releaseSoon(1200)}
 function handleSpeech(r:any){if(awarded.current||helpLock.current||speaking||parent||paused||rest||done)return;const text=r.text||'',confidence=r.result?.length?Math.min(...r.result.map((x:any)=>x.conf)):0;const candidates=stage==='words'?wordPool(5):levels.flatMap(l=>l[stage==='pictures'?'words':stage]);const verdict=classifyUtterance(text,confidence,target,candidates,stage==='letters'&&names[target]?[names[target]]:[]);if(verdict.kind==='rest'){stop();setPaused(true);return}if(verdict.kind==='correct'){setAttemptStatus('');success('local-speech');return}if(stage!=='letters'){const part=slowAttempt.current.accept(text,confidence,target);setSpeechProgress(part.progress);if(part.kind==='complete'){setAttemptStatus('');success('local-speech-parts');return}if(part.kind==='pending'){setAttemptStatus('Начало услышано. Продолжай, я жду.');return}}if(verdict.kind==='ignore'){setAttemptStatus('Звук услышан. Попробуй прочитать слово на карточке — можно по частям.');return}if(verdict.kind==='wrong'){setAttemptStatus('');wrongResponse(verdict.heard!,'local-speech');return}setHeard('');setFeedback({kind:'uncertain',text:'Не расслышал. Скажи ещё раз — я слушаю.'})}
 activitySink.current=phase=>{if(awarded.current||helpLock.current||speaking||parent||paused||rest||done||loadingSpeech)return;if(phase==='sound')setAttemptStatus('Слышу звук. Читай в своём темпе.');else setAttemptStatus(slowAttempt.current.progress?'Начало услышано. Продолжай, я жду.':'Попытка услышана, но слово пока не распознано. Попробуй ещё раз или послушай образец.');};
 resultSink.current=handleSpeech;
 function listen(){if(lessonMic){setLessonMic(false);stop();return}if(!settings.micConsent){setConsent(true);return}setLessonMic(true)}
 useEffect(()=>{if(!lessonMic||!settings.micConsent||mode!=='read'||parent||paused||rest||done)return;stop();const token=epoch.current;setListening(true);setLoadingSpeech(true);recognition.current=startLocalSpeech({deviceId:settings.micDevice,vocabulary:[...wordPool(5),...levels.flatMap(l=>[...(stage==='letters'?l.letters.map(x=>names[x]||x):[]),...l.syllables,...l.words]),...pictures.map(p=>p.word),'нет','да','привет','ошибка','я не хочу','я не буду','не надо','хватит','я устал','я устала','стоп','хочу отдохнуть'],onLevel:v=>{if(epoch.current===token)setMicLevel(v)},onSpectrum:v=>{if(epoch.current===token)setSpectrum(v)},onStatus:text=>{if(epoch.current===token&&!awarded.current)setFeedback({kind:'neutral',text})},onReady:()=>{if(epoch.current!==token)return;setLoadingSpeech(false);if(!awarded.current)setFeedback({kind:'neutral',text:'Я слушаю. Прочитай и сделай паузу.'});void navigator.mediaDevices.enumerateDevices().then(d=>setMicDevices(d.filter(x=>x.kind==='audioinput'))).catch(()=>{})},onActivity:phase=>{if(epoch.current===token)activitySink.current(phase)},onPartial:()=>{if(epoch.current===token)activitySink.current('sound')},onResult:r=>{if(epoch.current===token&&mounted.current)resultSink.current(r)},onError:text=>{if(epoch.current!==token)return;setLessonMic(false);setListening(false);setLoadingSpeech(false);setFeedback({kind:'uncertain',text})}});return()=>stop()},[lessonMic,settings.micConsent,index,stage,mode,parent,paused,rest,done,settings.unit,settings.micDevice]);
 useEffect(()=>{recognition.current?.setEnabled?.(!speaking&&!cooldown&&feedback.kind!=='success'&&!parent&&!paused&&!rest&&!done)},[speaking,cooldown,feedback.kind,parent,paused,rest,done,listening,loadingSpeech]);
 async function testMic(){if(micTesting){stop();setMicMessage('Проверка остановлена.');return}stop();const token=epoch.current;let stream:MediaStream|undefined,ctx:AudioContext|undefined,frame=0;const cleanup=()=>{cancelAnimationFrame(frame);stream?.getTracks().forEach(t=>t.stop());if(ctx&&ctx.state!=='closed')void ctx.close()};recognition.current={abort:cleanup};try{ctx=new AudioContext();await ctx.resume();stream=await navigator.mediaDevices.getUserMedia({audio:{deviceId:settings.micDevice?{exact:settings.micDevice}:undefined},video:false});if(epoch.current!==token){cleanup();return}const devices=await navigator.mediaDevices.enumerateDevices();if(epoch.current!==token){cleanup();return}setMicDevices(devices.filter(x=>x.kind==='audioinput'));const analyser=ctx.createAnalyser();analyser.fftSize=512;ctx.createMediaStreamSource(stream).connect(analyser);const data=new Float32Array(512);setMicTesting(true);setMicMessage('Скажи что-нибудь. Полоска показывает реальный звук микрофона.');let last=0;const tick=()=>{if(epoch.current!==token)return;analyser.getFloatTimeDomainData(data);let sum=0;for(const v of data)sum+=v*v;if(performance.now()-last>80){setMicLevel(Math.min(1,Math.sqrt(sum/data.length)*8));last=performance.now()}frame=requestAnimationFrame(tick)};tick()}catch(e){cleanup();setMicTesting(false);setMicMessage((e as Error).name==='NotAllowedError'?'Доступ запрещён. Разреши микрофон в настройках этого сайта.':'Не удалось открыть микрофон. Выбери другое устройство.')}}

 useEffect(()=>{if(mode!=='fly'||done)return;caughtIds.current.clear();flyNext.current=3;setFlyCards(Array.from({length:3},(_,i)=>({id:i,text:(deck.length?deck:pool)[i%(deck.length||pool.length)],caught:false})));setFlyInputStatus('Напечатай любую карточку, которую видишь.')},[mode,stage,settings.unit,done,deck]);
 useEffect(()=>{if(mode!=='fly'||paused||rest||parent||done)return;const caught=flyCards.filter(c=>c.caught);if(!caught.length)return;const t=setTimeout(()=>{setFlyCards(cards=>cards.map(c=>{if(!caught.some(x=>x.id===c.id))return c;const id=flyNext.current++;return {id,text:pool[Math.floor(Math.random()*pool.length)],caught:false}}))},1000);return()=>clearTimeout(t)},[flyCards,mode,paused,rest,parent,done]);
 function catchCard(){if(!answer.trim()||paused||rest||done)return;const card=flyCards.find(c=>!c.caught&&!caughtIds.current.has(c.id)&&checkTyped(answer,c.text));if(!card){setFlyInputStatus('Найди такой же на дорожке. Можно исправить ответ.');return}caughtIds.current.add(card.id);setFlyCards(cards=>cards.map(c=>c.id===card.id?{...c,caught:true}:c));setAnswer('');setFlyInputStatus(`Поймано: ${card.text}!`);setStars(n=>n+1);setHistory(h=>[...h,{at:new Date().toISOString(),target:card.text,stage,mode,result:'success',via:'catch'}].slice(-300));const completed=count+1;setCount(completed);if(completed>=settings.length)setDone(true);else if(completed%3===0){setRestIndex(i=>(i+1)%breaks.length);setRest(true)}}
 function showTypo(){const correction=findTypo(answer,target,picture?wordPool(5):[]);if(!correction)return false;setTypo(correction);setHint(false);setHeard('');setFeedback({kind:'neutral',text:correction.message});record('spelling-help','typed');if(settings.sound&&settings.autoSpeech)speak(correction.message);return true}
 function submit(){setTypo(null);if(mode==='fly'){catchCard();return}if(awarded.current)return;if(!answer.trim())return;if(!/[а-яё]/i.test(answer)){setFeedback({kind:'uncertain',text:'Переключи клавиатуру на русский язык.'});return}if(picture){const verdict=pictureAnswer(answer,target);if(verdict.kind==='exact')success('typed');else if(verdict.kind==='part'){setHint(false);setHeard('');setFeedback({kind:'neutral',text:verdict.message});record('observation','typed');if(settings.sound&&settings.autoSpeech)speak(verdict.message)}else if(verdict.kind==='related'||verdict.kind==='similar'){setScene(true);setHint(true);setFeedback({kind:'neutral',text:verdict.message});record('related','typed');if(settings.sound&&settings.autoSpeech)speak(verdict.message)}else{if(showTypo())return;setScene(true);setHint(true);setFeedback({kind:'uncertain',text:verdict.kind==='other'?verdict.message:'Напиши слово.'});record('help','typed')}return}if(checkTyped(answer,target))success('typed');else if(!showTypo())wrongResponse('','typed')}
 function next(skip=false){if(!skip&&!awarded.current)return;if(skip&&!awarded.current)record('skipped','manual');const nextCount=count+1;resetCard();setIndex(i=>i+1);setCount(nextCount);if(nextCount>=settings.length)setDone(true);else if(nextCount%3===0){setRest(true);setRestIndex(i=>(i+1)%breaks.length)}}
 function update<K extends keyof Settings>(key:K,value:Settings[K]){if(key==='micConsent'&&!value){setLessonMic(false);stop()}if(key==='unit'||key==='length'){setSession(n=>n+1);resetCard();setIndex(0);setCount(0);setDone(false);setRest(false)}setSettings(s=>({...s,[key]:value}))}
 function exportReport(){const text=['Читаем по шагам — результаты на этом устройстве','Дата;Материал;Раздел;Режим;Результат;Проверка',...history.map(h=>[h.at,h.target,h.stage,h.mode,h.result,h.via].join(';'))].join('\r\n');const url=URL.createObjectURL(new Blob(['\ufeff'+text],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='reading-progress.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const controller=new AbortController();try{Promise.resolve(context.registerTool({name:'get_reading_activity',description:'Read the current exercise and session progress without changing it.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute:(v:unknown)=>{if(v===null||typeof v!=='object'||Object.keys(v).length)throw Error('Expected an empty object');return {stage,mode,target,completed:count,total:settings.length,paused:paused||rest||parent,finished:done}}},{signal:controller.signal})).catch(()=>{})}catch{}return()=>controller.abort()},[stage,mode,target,count,settings.length,paused,rest,parent,done]);
 const currentStage=stages.find(s=>s.id===stage)!;
 return <main data-version="lab" className={settings.motion?'motion':'calm'}>
 <header><a className="brand" href="/" aria-label="Читаем по шагам"><BookOpen/><b>Читаем <span>по шагам</span></b><small className="lab-label">Чтение · версия 3</small></a><button onClick={()=>{stop();setParent(true)}}><Settings2 size={18}/><span>Для взрослого</span></button></header>
 <div className="shell"><aside><p>МОЯ ТРОПИНКА</p><nav aria-label="Разделы">{stages.map((s,i)=><button key={s.id} className={stage===s.id?'selected':''} aria-current={stage===s.id?'step':undefined} onClick={()=>navigate(s.id)}><b>0{i+1}</b><span>{s.name}</span>{stage===s.id&&<span className="stage-dot">●</span>}</button>)}</nav><div className="aside-note"><Leaf/><h3>В своём темпе</h3><p>Можно подумать,<br/>повторить и отдохнуть.</p></div><button className="break-link" onClick={()=>{stop();setRest(true)}}><Leaf size={18}/> Разминка</button></aside>
 <section className="lesson"><div className="lesson-top"><div><small>ШАГ 0{stages.findIndex(s=>s.id===stage)+1} · {stage==='pictures'?'НАЗЫВАЕМ ПРЕДМЕТЫ':stage==='words'?'ПЕРВЫЕ СЛОВА':levels[settings.unit].name}</small><h1>{currentStage.title}</h1></div><span className="pill"><Star size={17}/>{stars} <span className="desktop-word">звёзд</span></span></div>
 <div className="toolbar"><Tabs value={mode} onValueChange={v=>{if(stage==='pictures')return;navigate(stage,v as Mode)}}><TabsList className="mode-list"><TabsTrigger value="read" disabled={stage==='pictures'}><Mic/> Читаю</TabsTrigger><TabsTrigger value="fly" disabled={stage==='pictures'}><Keyboard/> Ловлю</TabsTrigger><TabsTrigger value="type"><ImageIcon/> Пишу</TabsTrigger></TabsList></Tabs><button className="quiet" onClick={()=>{stop();setPaused(true)}} aria-label="Пауза"><Pause size={18}/></button></div>
 <div className={'exercise '+feedback.kind}><div className="exercise-top"><span>Задание {Math.min(count+1,settings.length)} из {settings.length}</span><button className="quiet" onClick={()=>speak(task)} disabled={speaking} aria-label="Озвучить задание"><Volume2 size={21}/></button></div><Progress value={count/settings.length*100} aria-label="Прогресс занятия" className="lesson-progress"/>
 {done?<div className="completion"><span className="celebration" aria-hidden>🌟</span><h2>Ты позанимался. Здорово!</h2><p>Пройдено заданий: {count}. Теперь можно отдохнуть.</p><button className="primary" onClick={()=>{navigate(stage,mode);setRest(true)}}><Leaf/> Отдохнуть</button><button className="text-button" onClick={()=>{navigate(stage,mode)}}>Ещё короткое занятие <ArrowRight size={17}/></button></div>:<><h2>{task}</h2>
 {mode==='fly'?<div className={'catch-game '+(!settings.motion?'still':'')} aria-label="Дорожки с карточками"><div className="catch-instruction">Можно ловить в любом порядке</div>{flyCards.map((card,lane)=><div className="catch-lane" key={lane}><div key={card.id} className={'catch-token '+(card.caught?'caught':'')} data-token={card.text} style={{animationDuration:`${22+lane*5}s`,animationDelay:`-${lane*5}s`,animationPlayState:paused||parent||rest||done?'paused':'running'}}><span>{card.text}</span>{card.caught&&<Check size={23}/>}</div></div>)}</div>:picture?<div>{scene?<PictureScene word={target}/>:<div className="picture" role="img" aria-label="Картинка предмета для задания">{picture.icon}</div>}<button className="text-button scene-toggle" onClick={()=>setScene(v=>!v)}>{scene?'Первая картинка':'Посмотреть другую картинку'}</button></div>:<div className='reading' key={target+'-'+index} style={{animationPlayState:paused||parent||rest||listening||feedback.kind==='success'?'paused':'running'}} aria-label={target}>{Array.from(target).map((char,i)=><span key={i} className={(settings.color?(/[АЕЁИОУЫЭЮЯ]/.test(char)?'vowel':'consonant'):'')+(mistakes>0&&i===0?' first-focus':'')}>{char}</span>)}</div>}
 {mode==='read'?<button className="sample" onClick={()=>speak(stage==='letters'?(names[target]||target):target)} disabled={speaking}><Volume2 size={16}/>{stage==='letters'?'Послушать название':'Послушать образец'}</button>:<form className="answer-form" onSubmit={e=>{e.preventDefault();submit()}}><input ref={input} aria-label="Твой ответ" value={answer} onChange={e=>{if(typo){setTypo(null);setFeedback({kind:'neutral',text:'Исправь и проверь ещё раз.'})}setAnswer(e.target.value);if(feedback.kind==='error')setFeedback({kind:'neutral',text:'Попробуй ещё раз.'})}} disabled={feedback.kind==='success'||paused||parent||rest} placeholder={mode==='fly'?'Лови любой!':stage==='pictures'?'Напиши слово':'Напечатай здесь'} lang="ru" autoComplete="off" autoCorrect="off" spellCheck={false} maxLength={40}/><button className="check-button" type="submit" disabled={!answer.trim()||feedback.kind==='success'} aria-label="Проверить ответ"><Check/></button></form>}
 {mode==='read'&&lessonMic&&<div className={'voice-orbit '+(feedback.kind==='success'?'voice-success':'')}><div className="equalizer" role="img" aria-label={listening&&!speaking&&!cooldown?'Микрофон слушает':'Микрофон ждёт'}>{spectrum.map((v,i)=><i key={i} style={{height:`${8+(speaking||cooldown||feedback.kind==='success'?0:v)*48}px`}}/>)}</div><span>{loadingSpeech?'Готовлю микрофон…':feedback.kind==='success'?'Получилось!':speaking?'Послушай подсказку':cooldown?'Попробуем ещё раз':attemptStatus|| (micLevel>.025?'Слышу звук':'Я слушаю')}</span></div>}
 {mode==='read'&&speechProgress>0&&feedback.kind!=='success'&&<div className="slow-progress" aria-label="Услышанная часть слова">{Array.from(target).map((letter,i)=><span key={i} className={i<speechProgress?'heard-letter':''}>{letter}</span>)}<small>Продолжай с выделенной границы — я жду.</small></div>}
 {feedback.kind==='success'&&<div className="success-badge" aria-hidden="true"><Star/> <span>+1 звезда</span><Star/></div>}
 <div className={'feedback '+feedback.kind} role="status" aria-live="polite">{feedback.kind==='success'?<Check size={20}/>:feedback.kind==='error'?<RotateCcw size={18}/>:feedback.kind==='uncertain'?<HelpCircle size={18}/>:null}<span>{mode==='fly'?flyInputStatus:feedback.text}</span>{mode!=='fly'&&settings.sound&&<button className="feedback-speaker" aria-label="Озвучить объяснение" title="Озвучить объяснение" disabled={speaking} onClick={()=>speak(feedback.text)}><Volume2 size={19}/></button>}</div>
 {heard&&mode==='read'&&<div className="comparison"><div><small>Я услышал</small><b>{heard}</b></div><ArrowRight/><div className="expected"><small>А здесь</small><b>{target}</b></div></div>}
 {typo&&<div className="typo-help" aria-label="Подсказка: исправление букв"><div><small>Ты написал</small><div className="typo-letters">{typo.cells.map((c,i)=><span key={i} className={c.changed?'typo-mark':''} aria-label={c.before||'Место пропущенной буквы'}>{c.before||'·'}</span>)}</div></div><div><small>Исправь так</small><div className="typo-letters">{typo.cells.map((c,i)=><span key={i} className={c.changed?'typo-fix':''} aria-label={c.after||'Убрать лишнюю букву'}>{c.after||'·'}</span>)}</div></div></div>}
 {hint&&mode!=='fly'&&<div className="hint-box">{picture?<><p>{picture.hint}</p><p>Слово: <b>{target}</b></p><button className="sample" onClick={()=>speak(target)}><Volume2 size={16}/> Послушать слово</button></>:<><p>{mistakes>=3?'Найди такой же. Потом прочитай.':target.length>1?'Начни с первой буквы и соедини звуки.':'Посмотри на букву. Повтори за взрослым.'}</p><div className="sound-path">{Array.from(target).map((c,i)=><span key={i}><b className={i===0?'first-focus':''}>{c}</b>{i<target.length-1&&<ArrowRight size={20}/>}</span>)}</div>{mistakes>=2&&<button className="sample" onClick={()=>speak(target.toLowerCase())}><Volume2 size={18}/> Послушать вместе</button>}{mistakes>=3&&target.length>1&&<div className="support-choices">{[...new Set([Array.from(target).reverse().join(''),target])].map(v=><button key={v} onClick={()=>{if(v===target){setFeedback({kind:'neutral',text:`Да, это ${target}! Теперь прочитай.`});setHeard('');if(settings.sound&&settings.autoSpeech)speak(`Да! ${target.toLowerCase()}. Теперь прочитай.`)}else{setFeedback({kind:'error',text:`Посмотри: первая буква — ${target[0]}.`})}}}>{v}</button>)}</div>}{mistakes>=3&&<button className="text-button" onClick={()=>{stop();setRest(true)}}><Leaf size={16}/> Немного отдохнуть</button>}</>}</div>}
 {feedback.kind==='success'?<button className="primary" onClick={()=>next()}>Дальше <ArrowRight/></button>:mode==='read'?<><button className={'primary '+(listening?'listening':'')} onClick={listen} disabled={!supported||speaking}>{listening?<MicOff/>:<Mic/>}{lessonMic?(loadingSpeech?'Отменить подготовку':'Выключить микрофон'):'Начать урок с микрофоном'}</button>{!supported&&<p className="heard">Микрофон здесь недоступен. Можно прочитать взрослому.</p>}<details className="adult-check"><summary>Проверить вместе со взрослым</summary><p>Послушайте ребёнка и выберите результат.</p><div className="adult-actions"><button onClick={()=>{stop();success('adult')}}><Check/> Получилось</button><button onClick={()=>{setFeedback({kind:'uncertain',text:'Давай вместе. Послушай и повтори.'});setHint(true);setMistakes(n=>Math.max(2,n));record('help','adult');speak(target.toLowerCase())}}>Нужна помощь</button></div></details></>:<p className="keyboard-tip">Enter — проверить ответ</p>}
 <div className="exercise-footer">{mode!=='fly'&&<button className="text-button" onClick={()=>setHint(!hint)}><HelpCircle size={16}/>{hint?'Скрыть подсказку':'Подсказка'}</button>}<button className="text-button" onClick={()=>{if(mode==='fly'){setAnswer('');setFlyCards(cards=>cards.map(()=>{const id=flyNext.current++;return {id,text:pool[Math.floor(Math.random()*pool.length)],caught:false}}));setFlyInputStatus('Лови новые!')}else next(true)}}>{mode==='fly'?'Другие карточки':'Пропустить'} <ArrowRight size={16}/></button></div></>}
 </div><div className="foot"><Leaf size={16}/> {settings.motion?'Движение включено · можно остановиться в любой момент':'Без спешки и таймера'} <span>·</span> Отдых через каждые 3 задания</div>
 <div className="lesson-meta"><button className="text-button" onClick={()=>{stop();setParent(true)}}>Выбрать материал <ArrowRight size={14}/></button></div>
 </section></div>
 <Dialog open={parent} onOpenChange={v=>{stop();setParent(v)}}><DialogContent className="parent-dialog"><DialogTitle className="dialog-heading">Настроим занятие</DialogTitle><DialogDescription>Настройки и результаты сохраняются только в этом браузере на этом устройстве.</DialogDescription>
 <div className="setting"><label>Материал</label><Select value={String(settings.unit)} onValueChange={v=>{if(v!==null)update('unit',Number(v))}}><SelectTrigger aria-label="Материал занятия"><SelectValue>{levels[settings.unit].name}</SelectValue></SelectTrigger><SelectContent>{levels.map((l,i)=><SelectItem key={i} value={String(i)}>{l.name}</SelectItem>)}</SelectContent></Select></div>
 <div className="setting"><label>Длина занятия</label><Select value={String(settings.length)} onValueChange={v=>{if(v!==null)update('length',Number(v))}}><SelectTrigger aria-label="Количество заданий"><SelectValue>{settings.length} заданий</SelectValue></SelectTrigger><SelectContent>{[3,5,8].map(n=><SelectItem key={n} value={String(n)}>{n} заданий</SelectItem>)}</SelectContent></Select></div>
 {([['motion','Анимации и эффекты','Плавное движение и звёздочка за успех. Можно отключить.'],['sound','Озвучка и музыка','Подсказки при чтении. Музыка в паузе — только по кнопке.'],['slow','Медленная озвучка','Больше времени, чтобы расслышать.'],['color','Цветные буквы','Гласные — терракотовые, согласные — зелёные.']] as const).map(([k,title,sub])=><div className="setting" key={k}><label htmlFor={'setting-'+k}><b>{title}</b><small>{sub}</small></label><Switch id={'setting-'+k} checked={settings[k]} onCheckedChange={v=>update(k,v)}/></div>)}
 <div className="setting"><label htmlFor="speech-mode"><b>Озвучка подсказок и ответов</b><small>По кнопке с динамиком или сразу после ответа ребёнка.</small></label><Select value={settings.autoSpeech?'auto':'button'} onValueChange={v=>{if(v!==null){stop();update('autoSpeech',v==='auto')}}}><SelectTrigger id="speech-mode" aria-label="Режим озвучки" disabled={!settings.sound}><SelectValue>{settings.autoSpeech?'Автоматически':'По кнопке'}</SelectValue></SelectTrigger><SelectContent><SelectItem value="button">По кнопке</SelectItem><SelectItem value="auto">Автоматически</SelectItem></SelectContent></Select></div>
 <div className="mic-settings"><h3>Микрофон</h3><Select value={settings.micDevice||'default-device'} onValueChange={v=>{stop();update('micDevice',v==='default-device'?'':String(v))}}><SelectTrigger aria-label="Устройство микрофона"><SelectValue>{micDevices.find(d=>d.deviceId===settings.micDevice)?.label||'Микрофон по умолчанию'}</SelectValue></SelectTrigger><SelectContent><SelectItem value="default-device">Микрофон по умолчанию</SelectItem>{micDevices.filter(d=>d.deviceId&&d.deviceId!=='default').map((d,i)=><SelectItem key={d.deviceId} value={d.deviceId}>{d.label||`Микрофон ${i+1}`}</SelectItem>)}</SelectContent></Select><button onClick={testMic}>{micTesting?<MicOff size={16}/>:<Mic size={16}/>} {micTesting?'Остановить проверку':'Проверить микрофон'}</button><meter min={0} max={1} value={micLevel} aria-label="Проверка громкости микрофона"/><p>{micMessage}</p></div>
 <div className="parent-info"><h3>Как заниматься</h3><p>Буквы и слоги следуют выбранному набору. В разделе «Слова» — отдельный набор первых слов, включая ещё не изученные буквы; помогайте с ними. В новом занятии порядок перемешивается, одинаковые карточки не идут подряд. В паузе можно выбрать игру или движение.</p><p>Начните с 3–5 заданий. Один экран — одно действие. Можно отвечать голосом, с клавиатуры или вместе со взрослым. Остановитесь раньше, если ребёнок устал. Усложнение выбирает взрослый; все разделы доступны.</p><p>На кнопке «Послушать название» звучит название буквы. Для слияния в слог взрослый показывает именно звук: «м», а не «эм». Образец слога произносится целиком.</p><h3>О микрофоне</h3><p>Автораспознавание — подсказка, а не оценка произношения. Детская речь и отдельные слоги могут распознаваться неверно. Уверенно распознанный другой учебный слог подсвечивается мягким красным и сравнивается с заданием. Если распознавание не уверено — оранжевый, без счёта ошибок. Посторонняя речь не выводится. После двух ошибок появляется образец, после трёх — дополнительная помощь. Ручная оценка доступна в каждом задании.</p><p>Речь распознаётся прямо на устройстве с помощью Vosk. При первом запуске загружается русская модель (около 45 МБ). Голос не отправляется на сервер и не сохраняется. Для загрузки нужен интернет; для чтения — разрешение микрофона. Индикатор показывает реальный уровень звука. В настройках можно выбрать другое устройство.</p>{settings.micConsent&&<button className="text-button" onClick={()=>update('micConsent',false)}>Выключить согласие на распознавание</button>}
 <h3>Прогресс</h3><p>{stars} звёзд · записей в журнале: {history.length}. Пропуски и просьбы о помощи сохраняются отдельно от верных ответов. Последние 300 записей.</p><button onClick={exportReport} disabled={!history.length}><Download size={17}/> Скачать результаты</button>{storageWarning&&<p className="warning">{storageWarning}</p>}
 <details className="sources"><summary>Учебник и источники</summary><p>Аксёнова А. К., Комарова С. В., Шишкова М. И. «Букварь», часть 1. Проверены страницы 40–53: М → обратные слоги → прямые слоги → О → Х → С. Последующие наборы и игры — авторское дополнение, не полный цифровой учебник. Иллюстрации книги не переиздаются.</p><a href="http://i.internat5vlg.ru/u/ea/abe0f684c111ea83f3b5f3c7fe5d55/-/Букварь%201%20класс%20часть%201%20АОП%20%28Аксенова%29.pdf" target="_blank" rel="noreferrer">Найденный PDF учебника ↗</a><a href="https://www.cdc.gov/adhd/treatment/classroom.html" target="_blank" rel="noreferrer">CDC: короткие задания, обратная связь и перерывы ↗</a><a href="https://www.autism.org.uk/advice-and-guidance/education/getting-help-at-school/what-can-my-autistic-child-get-support-with-at-school" target="_blank" rel="noreferrer">National Autistic Society: понятные шаги и спокойная среда ↗</a><p>Это учебный тренажёр, не медицинская программа. Темп и подход подбираются под конкретного ребёнка.</p></details></div><button className="primary" onClick={()=>{stop();setParent(false)}}>Вернуться к занятию <ArrowRight size={18}/></button>
 </DialogContent></Dialog>
 <Dialog open={paused||rest} onOpenChange={v=>{stop();if(!v){setPaused(false);setRest(false)}}}><DialogContent className="rest-dialog hub-dialog"><DialogTitle className="dialog-heading">Время отдохнуть</DialogTitle><DialogDescription>Можно выбрать игру, размяться или просто побыть в тишине.</DialogDescription><RestHub motion={settings.motion} autoSpeech={settings.autoSpeech} sound={settings.sound} onSpeak={speak} onReturn={()=>{stop();setPaused(false);setRest(false)}}/></DialogContent></Dialog>
 <Dialog open={consent} onOpenChange={setConsent}><DialogContent><DialogTitle className="dialog-heading">Взрослому: включить микрофон?</DialogTitle><DialogDescription>Приложение загрузит русскую модель и будет распознавать речь на этом устройстве. Голос не отправляется на сервер и не сохраняется. Автопроверка может ошибаться, особенно на отдельных буквах и слогах.</DialogDescription><button className="primary" onClick={()=>{update('micConsent',true);setConsent(false);setLessonMic(true)}}>Разрешаю распознавание</button><button onClick={()=>setConsent(false)}>Будем читать вместе</button></DialogContent></Dialog>
 </main>
}
